name: Check PR Mentions

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  

jobs:
  check-mentions:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure GitHub CLI and jq are installed
        run: |
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            sudo apt-get update && sudo apt-get install -y gh
          fi
          
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            sudo apt-get install -y jq
          fi

      - name: Get PR Details from Notifications
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          TARGET_REPO="saitama951/runtime"
          echo "Checking PR mentions in repository: $TARGET_REPO"
          PR_URL=$(gh api notifications -H "Authorization: token $GH_TOKEN" \
            --jq '.[] | select(.repository.full_name=="'"$TARGET_REPO"'") | select(.reason=="mention") | select(.subject.type=="PullRequest") | .subject.url' | head -n1)
          if [ -z "$PR_URL" ]; then
              echo "No relevant PR mention found."
              exit 1
          fi
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          echo "PR Number: $PR_NUMBER"   

          MENTION_COMMENT=$(gh api repos/$TARGET_REPO/issues/$PR_NUMBER/comments --jq '.[] | select(.body | contains("@ShreyaLaxminarayan"))' | tail -n1)
          
          if [ -z "$MENTION_COMMENT" ]; then
              echo "No mention found in PR comments."
              exit 0
          fi
          MENTIONING_USER=$(echo "$MENTION_COMMENT" | jq -r '.user.login')
          echo "Bot was mentioned by: @$MENTIONING_USER"

          LATEST_COMMIT=$(gh pr view "$PR_NUMBER" --repo "$TARGET_REPO" --json commits -q '.commits[-1].oid')
          if [ -z "$LATEST_COMMIT" ]; then
              echo "Failed to fetch the latest commit from PR #$PR_NUMBER"
              exit 1
          fi
         
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
          echo "MENTIONING_USER=$MENTIONING_USER" >> $GITHUB_ENV
          
          GIST_DESC="Logs for PR #$PR_NUMBER - Commit $LATEST_COMMIT"
          EXISTING_GIST=$(gh gist list --json id,description -q \ '.[] | select(.description=="'"$GIST_DESC"'")')
          if [ -n "$EXISTING_GIST" ]; then
              GIST_ID=$(echo "$EXISTING_GIST" | jq -r '.id')
              GIST_URL="https://gist.github.com/$GIST_ID"
              echo "gist: $GIST_URL"
              gh pr comment "$PR_NUMBER" --repo "$TARGET_REPO" --body "@$MENTIONING_USER. Please check logs 🔗 [View Full Logs]($GIST_URL)"
                exit 0 
          fi

      - name: Trigger Build Workflow
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh workflow run build.yml -f pr_number=$PR_NUMBER -f commit_id=$LATEST_COMMIT -f mentioning_user=$MENTIONING_USER --repo ShreyaLaxminarayan/GITHUB-BOT
