name:  BUILD DOTNET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]


jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./scripts

    steps:
    - uses: actions/checkout@v4
    - run: chmod +x automate-runtime.sh 
    - run: ./automate-runtime.sh
    
