name: Setup Dotnet SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  setup-dotnet-sdk:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh mutt
      - name: clone
        run: |
          git clone https://github.com/dotnet/runtime.git
          cd runtime
        
      - name: Set up GitHub CLI authentication
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Create directories
        run: |
          sudo mkdir -p sdk packages
          version=$(jq -r .sdk.version $GITHUB_WORKSPACE/runtime/global.json)
          mkdir -p $GITHUB_WORKSPACE/runtime/.dotnet/

      - name: Try extracting SDK from tar.gz
        run: |
          version=$(jq -r .sdk.version $GITHUB_WORKSPACE/runtime/global.json)
          tar -xzf $GITHUB_WORKSPACE/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory $GITHUB_WORKSPACE/runtime/.dotnet/
        continue-on-error: true 

      - name: Download SDK from GitHub Releases if extraction fails
        run: |
          if [ $? -ne 0 ]; then
            echo "Failed to extract SDK from tar.gz, downloading from GH Releases" >> $GITHUB_WORKSPACE/error.log
            pushd sdk
            gh release download v${version} --repo IBM/dotnet-s390x --pattern dotnet-sdk-${version}-linux-s390x.tar.gz
            if [ $? -ne 0 ]; then
              echo "Failed to get the dotnet host SDK version ${version}. Please build the SDK" >> $GITHUB_WORKSPACE/error.log
              exit 1
            fi
            popd
            pushd packages
            gh release download v${version} --repo IBM/dotnet-s390x --pattern '*linux-s390x*.nupkg'
            tar -xzf $GITHUB_WORKSPACE/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory $GITHUB_WORKSPACE/runtime/.dotnet/
            popd
          fi

