name:  BUILD DOTNET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]


jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./scripts
      
    steps:
    - uses: actions/checkout@v4
    - name: Clone the repository
    - run: |
          BASEDIR=$(pwd)
          git clone --branch ${GITHUB_REF_NAME:-main} https://github.com/dotnet/runtime
          pushd runtime
          commit_id=$(git show HEAD --pretty=format:"%h" --no-patch)
          echo "commit id: ${commit_id}" > commit_id.txt
          popd
    - name: Extract sdk
    - name: Build runtime
    - name: Shoot email
    - run: chmod +x automate-runtime.sh 
    - run: ./automate-runtime.sh
    
    
