name:  BUILD DOTNET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]


jobs:
  build:
    runs-on: self-hosted
      
    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get install -y jq mutt gh
    - run: |
        BASEDIR=$(pwd)
        git clone --branch ${GITHUB_REF_NAME:-main} https://github.com/dotnet/runtime
        cd runtime
        commit_id=$(git show HEAD --pretty=format:"%h" --no-patch)
        echo "commit id: ${commit_id}" > commit_id.txt
        cd ..
    - run: |
        sudo mkdir -p /workspace/sdk /workspace/packages
        if [ ! -f "${BASEDIR}/runtime/global.json" ]; then
            echo "global.json not found at ${BASEDIR}/runtime/global.json"
        exit 1
        fi
        version=$(jq .sdk.version ${BASEDIR}/runtime/global.json | tr -d '"')
        echo "SDK version: ${version}"
        echo "SDK version: ${version}"
        sudo mkdir -p /workspace/runtime/.dotnet/
        if ! tar -xzf ${BASEDIR}/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory /workspace/runtime/.dotnet/; then
          echo "Failed to extract SDK. Trying to download it."
          export GH_TOKEN=${{ secrets.PAT_TOKEN }}
          cd /workspace/sdk
          gh release download v${version} --repo IBM/dotnet-s390x --pattern dotnet-sdk-${version}-linux-s390x.tar.gz || exit 1
          cd ..
          cd /workspace/packages
          gh release download v${version} --repo IBM/dotnet-s390x --pattern '*linux-s390x*.nupkg' || exit 1
          tar -xzf ${BASEDIR}/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory /workspace/runtime/.dotnet/
          cd ..
        fi
        
        

    
