name:  BUILD DOTNET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]


jobs:
  build:
    runs-on: self-hosted
      
    steps:
    - uses: actions/checkout@v4
    - run: |
          BASEDIR=$(pwd)
          git clone --branch ${GITHUB_REF_NAME:-main} https://github.com/dotnet/runtime
          pushd runtime
          commit_id=$(git show HEAD --pretty=format:"%h" --no-patch)
          echo "commit id: ${commit_id}" > commit_id.txt
          popd
    
    
