name: Check PR Mentions

on:
  push:
    branches:
      - main
  workflow_dispatch:  
  # schedule:
  #   - cron: '0 * * * *'  

jobs:
  check-mentions:
    runs-on: self-hosted  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure GitHub CLI and jq are installed
        run: |
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            sudo apt-get update && sudo apt-get install -y gh
          fi
          
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            sudo apt-get install -y jq
          fi          

      - name: Get PR Details from Notifications
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          
          TARGET_REPO="saitama951/runtime"
          echo "Checking PR mentions in repository: $TARGET_REPO"
          PR_URL=$(gh api notifications -H "Authorization: token $GH_TOKEN" \
            --jq '.[] | select(.repository.full_name=="'"$TARGET_REPO"'") | select(.reason=="mention") | select(.subject.type=="PullRequest") | .subject.url' | head -n1)
          if [ -z "$PR_URL" ]; then
              echo "No relevant PR mention found."
              exit 1
          fi
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          echo "$PR_NUMBER"   
          LATEST_COMMIT=$(gh pr view "$PR_NUMBER" --repo "$TARGET_REPO" --json commits -q '.commits[-1].oid')
          if [ -z "$LATEST_COMMIT" ]; then
              echo "Failed to fetch the latest commit from PR #$PR_NUMBER"
              exit 1
          fi

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
          
          

      - name: Clone Repository
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          
          echo "Cloning repository..."
          gh repo clone saitama951/runtime
          cd runtime
          git config --global user.email "raoshreya412@gmail.com"
          git config --global user.name "ShreyaLaxminarayan"

          echo "Fetching latest changes..."
          git fetch origin main
          git checkout main
          
          echo "Latest commit ID: $LATEST_COMMIT"
          
          echo "Cherry-picking latest commit..."
          git cherry-pick $LATEST_COMMIT
          
          



          
