name: Check PR Mentions

on:
  push:
    branches:
      - main
  workflow_dispatch:  
  schedule:
    - cron: '0 * * * *'  

jobs:
  check-mentions:
    runs-on: self-hosted  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure GitHub CLI and jq are installed
        run: |
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            sudo apt-get update && sudo apt-get install -y gh
          fi
          
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            sudo apt-get install -y jq
          fi

      - name: Fetch PR Mention Without gh auth login
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GH_TOKEN directly
        run: |
          TARGET_REPO="saitama951/runtime"
          PR_FILE="$GITHUB_WORKSPACE/pr_numbers.txt"

          echo "Checking PR mentions in repository: $TARGET_REPO"

          PR_URL=$(gh api notifications -H "Authorization: token $GH_TOKEN" \
            --jq '.[] | select(.repository.full_name=="'"$TARGET_REPO"'") | select(.reason=="mention") | select(.subject.type=="PullRequest") | .subject.url' | head -n1)

          if [ -z "$PR_URL" ]; then
              echo "No relevant PR mention found."
              exit 1
          fi

          # Extract PR number and title
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          PR_TITLE=$(gh api "repos/$TARGET_REPO/pulls/$PR_NUMBER" -H "Authorization: token $GH_TOKEN" --jq '.title')

          echo "Mentioned in PR #$PR_NUMBER: $PR_TITLE"

          # Save PR details to a file
          echo "PR #$PR_NUMBER: $PR_TITLE" > "$PR_FILE"
          echo "Successfully saved PR mention to $PR_FILE."

      # - name: Upload PR Mentions
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pr_mentions
      #     path: pr_numbers.txt
